os: osx
osx_image: xcode10.2

addons:
  homebrew:
    packages:
    - boost
    - openssl
    - rapidjson
    - qt
    - p7zip
    
compiler: clang

script:
  - mkdir build && cd build
  - /usr/local/opt/qt/bin/qmake .. && make -j8
  - /usr/local/opt/qt/bin/macdeployqt chatterino.app -dmg

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
      secure: $SECURE_GITHUB_KEY
  file: "chatterino2.dmg"
  prerelease: true
  on:
    tags: false
    branch: osx-ci-test
