os: osx
osx_image: xcode10.2

addons:
  homebrew:
    packages:
    - boost
    - openssl
    - rapidjson
    - qt
    - p7zip
    
compiler: clang

script:
  - mkdir build && cd build
  - /usr/local/opt/qt/bin/qmake .. && make -j8
  - /usr/local/opt/qt/bin/macdeployqt chatterino.app -dmg

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=nightly-mac-0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Nightly last change - $TRAVIS_COMMIT_MESSAGE"
  - git push -q https://$GITHUB_KEY@github.com/fourtf/chatterino2 --tags
  - ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_KEY
  file: "chatterino2.dmg"
  prerelease: true
  on:
    tags: false
    branch: osx-ci-test
