version: 2
jobs:
  build:
    docker:
      - image: ubuntu:disco

    steps:
      - checkout

      - run:
          name: Fetch submodule
          command: git submodule update --init --recursive

      - run:
          name: Install required packages
          command: apt update && apt install -y git qt5-qmake qt5-default qtmultimedia5-dev libqt5svg5-dev libboost-dev libssl-dev libboost-system-dev libboost-filesystem-dev

      - run:
          name: Build
          command: mkdir build && cd build && qmake .. && make -j
